### ISSUE TITLE
mac上找不到npm包主页

### ISSUE THREAD

**Issue by fyhhub** [Simon-He95/vscode-open-pkg#2]
![image](https://github.com/Simon-He95/vscode-open-pkg/assets/38740836/11d058ed-0637-4cfd-97b9-4e6ae2ad6ad4)

**Comment by Simon-He95** [comment]
可能这个包并没有设置主页，需要检查这个npm包

**Comment by fyhhub** [comment]
所有包都不行  比如vue

![image](https://github.com/Simon-He95/vscode-open-pkg/assets/38740836/b1567a70-6978-4a47-af64-94aea8c97cdb)

**Comment by Simon-He95** [comment]
你应该是win电脑吧，可能win和mac在获取数据上有一些差异，我回头找个win调试一下

**Comment by fyhhub** [comment]
> 你应该是win电脑吧，可能win和mac在获取数据上有一些差异，我回头找个win调试一下

我是mac的不行，有可能原因，我有两台电脑，一个在win上用了，然后账户共享了插件，mac上就不行了？

**Comment by Simon-He95** [comment]
> > 你应该是win电脑吧，可能win和mac在获取数据上有一些差异，我回头找个win调试一下
> 
> 我是mac的不行，有可能原因，我有两台电脑，一个在win上用了，然后账户共享了插件，mac上就不行了？

你可以尝试在mac上重新下载一下，因为我也是mac上使用，是没有问题的
